version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout

      {% raw %}
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "environment.yml" }}
      #     - v1-dependencies-
      {% endraw %}

      - run:
          name: install dependencies
          command: |
            # conda env create -q || conda env update -q
            # source activate adj
            conda install -qy conda-build anaconda-client pytest pytest-cov
            conda config --set auto_update_conda no
            conda info -a
            conda build conda.recipe --no-test
            conda install --use-local {{ cookiecutter.package_name }}

      {% raw %}
      # - save_cache:
      #     paths:
      #       - /opt/conda
      #     key: v1-dependencies-{{ checksum "environment.yml" }}
      {% endraw %}

      - run:
          name: run tests
          command: |
            # source activate adj
            pytest --color=yes -v --cov={{ cookiecutter.package_name }} tests
            conda install -c conda-forge codecov
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
